### ISSUE TITLE
URLSchemas work, but the url is not passed to the function

### ISSUE THREAD

**Issue by AndersGerner** [hypery2k/nativescript-urlhandler#51]
It doesn't seem that the function handleOpenUrl is ever fired.

I have tried in my main-page.js:

```
handleOpenURL(function(appURL) {
	console.log("Hello " + appURL);
});
```

But nothing happens and no error is giving.

Is there a demo app for this project?

**Comment by hypery2k** [comment]
you can take a look at the [end2end test app](https://github.com/hypery2k/nativescript-urlhandler/tree/master/test/e2e). Otherwise follow the [install](https://github.com/hypery2k/nativescript-urlhandler#android) instructions. 

If it's not working please tell more about your concrete setup, see [here](https://github.com/hypery2k/nativescript-urlhandler/blob/master/CONTRIBUTING.md), as mentioned when opening a new issue.

**Comment by AndersGerner** [comment]
Thanks for your input @hypery2k I have tried to use the pure javascript version. The app is opening on my schema: "becf", but the function and URL is not run/passed. 

Would I be able to hire you to get my app to work?
Please contact me at agn@cphcloud.com as soon as possible. We need to deliver early next week. If you find any issues and create solutions, we'll of course share them in your plugin with everyone else :)

**Comment by hypery2k** [comment]
I think you didn't call the `handleOpenURL` soon enough. Try again with *nativescript-urlhandler@1.1.0-develop-67* and check if you see this error in the console:
```
No callback provided. Please ensure that you called "handleOpenURL" during application init!
```
